# Generated by Django 5.0.1 on 2024-02-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='updated_by',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
